name: test

on:
  push:
    branches: [main]
  pull_request:
env:
  DOCKER_HOST_IP: 127.0.0.1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: add kafka repo key
        run: wget -qO - https://packages.confluent.io/deb/4.0/archive.key | sudo apt-key add -

      - name: add kafka binary repo
        run: sudo add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/4.0 stable main"

      - name: install kafka binary
        run: sudo apt-get install confluent-platform-oss-2.11

      - name: run test multiple-schema-registry
        run: script/test docker-compose.yml 7
